const fs = require('fs');
const path = require('path');

/**
 * System Coherence Monitor — Generate Report (CJS)
 */

module.exports = {
  name: 'scm-report',

  async execute(params) {
    // Report writing does not require auth; keep it runnable even in unauth contexts.
    const outputPath =
      params.outputPath ||
      'C:/Users/jacks/OneDrive/Desktop/agnt-evo/agnt-auditor/coherence_report_latest.md';

    const report = params.reportData || {};
    const lines = [];

    const iso = new Date().toISOString();
    const day = iso.slice(0, 10); // YYYY-MM-DD

    lines.push('# System Coherence Report');
    lines.push('');
    lines.push(`<context date="${day}" />`);
    lines.push('');
    lines.push(`> Generated: ${iso}`);
    lines.push('');
    lines.push(`**Coherence Score: ${report.coherence_score ?? 'N/A'}/100**`);
    lines.push('');

    if (report.system_overview) {
      lines.push('## System Overview');
      lines.push('');
      const ov = report.system_overview;
      if (ov.api_health || ov.workflows_health) {
        lines.push(`- **API Health:** ${ov.api_health ?? 'N/A'}`);
        lines.push(`- **Workflow Service Health:** ${ov.workflows_health ?? 'N/A'}`);
      }
      if (ov.total_plugins != null || ov.total_tools != null) {
        lines.push(`- **Plugins:** ${ov.total_plugins ?? 'N/A'} | **Tools:** ${ov.total_tools ?? 'N/A'}`);
      }
      lines.push(`- **Total Workflows:** ${ov.total_workflows ?? 'N/A'} (active: ${ov.active ?? 'N/A'}, stopped: ${ov.stopped ?? 'N/A'}, inactive: ${ov.inactive ?? 'N/A'})`);
      lines.push(`- **Total Executions:** ${ov.total_executions ?? 'N/A'} (errors: ${ov.total_errors ?? 'N/A'})`);
      lines.push(`- **Total Credits:** ${typeof ov.total_credits === 'number' ? ov.total_credits.toFixed(1) : (ov.total_credits ?? 'N/A')}`);
      lines.push('');
    }

    if (Array.isArray(report.anomalies) && report.anomalies.length > 0) {
      lines.push('## Anomalies Detected');
      lines.push('');
      for (const a of report.anomalies) {
        const sev = String(a.severity || '').toLowerCase();
        const icon = sev === 'critical' ? '🔴' : sev === 'high' ? '🟠' : '🟡';
        lines.push(`- ${icon} **[${String(a.severity || 'unknown').toUpperCase()}]** ${a.type}: ${a.message}`);
      }
      lines.push('');
    } else {
      lines.push('## Anomalies');
      lines.push('');
      lines.push('✅ No anomalies detected.');
      lines.push('');
    }

    if (Array.isArray(report.workflow_analysis)) {
      lines.push('## Workflow Analysis');
      lines.push('');
      lines.push('| Workflow | Status | Executions | Errors | Error Rate | Credits |');
      lines.push('|----------|--------|------------|--------|------------|---------|');
      for (const wf of report.workflow_analysis) {
        const execs = Number(wf.executions || 0);
        const errs = Number(wf.errors || 0);
        const er = execs > 0 ? `${(Number(wf.errorRate || 0) * 100).toFixed(0)}%` : 'N/A';
        const credits = typeof wf.credits === 'number' ? wf.credits.toFixed(1) : (wf.credits ?? '0');
        const name = String(wf.name || 'Unknown').slice(0, 30);
        lines.push(`| ${name} | ${wf.status} | ${execs} | ${errs} | ${er} | ${credits} |`);
      }
      lines.push('');
    }

    if (Array.isArray(report.recommendations)) {
      lines.push('## Recommendations');
      lines.push('');
      for (const r of report.recommendations) lines.push(`- ${r}`);
      lines.push('');
    }

    lines.push('---');
    lines.push(`*Generated by System Coherence Monitor v1.0.0 at ${iso}*`);

    const content = lines.join('\n');

    try {
      fs.mkdirSync(path.dirname(outputPath), { recursive: true });
      fs.writeFileSync(outputPath, content, 'utf8');
    } catch (e) {
      return { status: 'error', error: 'Failed to write report: ' + (e?.message || String(e)) };
    }

    return {
      status: 'success',
      outputPath,
      lineCount: lines.length,
      content
    };
  }
};
